
version: '3.4'
services:

  # 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    stdin_open: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongovol:/data/db

  # 
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    restart: always 
    stdin_open: true  
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb

  # 
  api:
    # image: 'penkong/devref-back-typescript-rest-express-pg-typeorm-auth'
    build: 
      context: ../api
      dockerfile: Dockerfile.dev
    restart: always
    stdin_open: true
    depends_on:
      - mongodb
    volumes: 
      - /app/node_modules 
      - ../server:/app
    environment:
      - PORT=5002
      - DBURL=mongodb://<MONGOUSER>:<MONGOPASS>@mongodb:27017
      - DBNAME=vanillanodemongo
      - NODE_ENV=development
      - MONGOPASS=root
      - MONGOUSER=secret
      - CORS=http://localhost:3000
      - JWT_KEY=uy6hw65hywtrnbewhnterwhg
      - JWT_TTL=365d
    ports: 
      - 5002:5002
  
volumes:
  mongovol:
    driver: local